var RpcDefine = {
	JOIN_COIN_TABLE_REQ: [40000, "JOIN_COIN_TABLE_REQ"],
	JOIN_COIN_TABLE_RESP: [40001, "JOIN_COIN_TABLE_RESP"],
	BET_REQ: [40002, "BET_REQ"],
	BET_RESP: [40003, "BET_RESP"],
	PUSH_BET_MSG: [40005, "PUSH_BET_MSG"],
	BET_AGAIN_REQ: [40006, "BET_AGAIN_REQ"],
	BET_AGAIN_RESP: [40007, "BET_AGAIN_RESP"],
	UNDO_BET_REQ: [40008, "UNDO_BET_REQ"],
	UNDO_BET_RESP: [40009, "UNDO_BET_RESP"],
	USER_RECONNECT_REQ: [40010, "USER_RECONNECT_REQ"],
	PUSH_USER_RECONNECT_RESP: [40011, "PUSH_USER_RECONNECT_RESP"],
	PUSH_RECONNECT_DATA_RESP: [40013, "PUSH_RECONNECT_DATA_RESP"],
	PUSH_RECONNECT_QUIT_RESP: [40015, "PUSH_RECONNECT_QUIT_RESP"],
	PUSH_STATE_CHANGE_MSG: [40017, "PUSH_STATE_CHANGE_MSG"],
	PUSH_SENDCARD_MSG: [40019, "PUSH_SENDCARD_MSG"],
	PUSH_ROUND_RESULT_MSG: [40021, "PUSH_ROUND_RESULT_MSG"],
	PUSH_REMAINTIME_MSG: [40023, "PUSH_REMAINTIME_MSG"],
	USER_QUIT_REQ: [40024, "USER_QUIT_REQ"],
	USER_QUIT_RESP: [40025, "USER_QUIT_RESP"],
	PUSH_USER_EXIT: [40027, "PUSH_USER_EXIT"],
	FORCE_OFFLINE_REQ: [40028, "FORCE_OFFLINE_REQ"],
	FORCE_OFFLINE_RESP: [40029, "FORCE_OFFLINE_RESP"],
	PUSH_DELAYQUIT_OFFLINE_MSG: [40031, "PUSH_DELAYQUIT_OFFLINE_MSG"],
	PUSH_KICKEDOUT_MSG: [40033, "PUSH_KICKEDOUT_MSG"],
	USER_STAY_IN_GAME_REQ: [40034, "USER_STAY_IN_GAME_REQ"],
	SET_CARDS_TEST: [40036, "SET_CARDS_TEST"],
	// SET_CARDS_TEST: [40038, "SET_CARDS_TEST"],
	// SET_CARDS_TEST: [40039, "SET_CARDS_TEST"],
	// SET_CARDS_TEST: [40040, "SET_CARDS_TEST"],
	// SET_CARDS_TEST: [40041, "SET_CARDS_TEST"],


}


module.exports = {
	RpcDefine: RpcDefine
};
