var RpcDefine = {
	JOIN_COIN_TABLE_REQ: [40000, "JOIN_COIN_TABLE_REQ"],
	JOIN_COIN_TABLE_RESP: [40001, "JOIN_COIN_TABLE_RESP"],
	GETTABLELIST_REQ: [40002, "GETTABLELIST_REQ"],
	GETTABLELIST_RESP: [40003, "GETTABLELIST_RESP"],
	FREEHANDS_REQ: [40004, "FREEHANDS_REQ"],
	FREEHANDS_RESP: [40005, "FREEHANDS_RESP"],
	VIDEO_CONTROL_REQ: [40006, "VIDEO_CONTROL_REQ"],
	DEALCARD_REQ: [40008, "DEALCARD_REQ"],
	DEALCARD_RESP: [40009, "DEALCARD_RESP"],
	USER_RECONNECT_REQ: [40010, "USER_RECONNECT_REQ"],
	USER_RECONNECT_RESP: [40011, "USER_RECONNECT_RESP"],
	PUSH_RECONNECT_DATA_MSG: [40013, "PUSH_RECONNECT_DATA_MSG"],
	PUSH_RECONNECT_QUIT_MSG: [40015, "PUSH_RECONNECT_QUIT_MSG"],
	BET_REQ: [40016, "BET_REQ"],
	BET_RESP: [40017, "BET_RESP"],
	UNDO_BET_REQ: [40018, "UNDO_BET_REQ"],
	UNDO_BET_RESP: [40019, "UNDO_BET_RESP"],
	RESET_SUBTABLE_REQ: [40020, "RESET_SUBTABLE_REQ"],
	RESET_SUBTABLE_RESP: [40021, "RESET_SUBTABLE_RESP"],
	CHANGE_SUBTABLE_REQ: [40022, "CHANGE_SUBTABLE_REQ"],
	CHANGE_SUBTABLE_RESP: [40023, "CHANGE_SUBTABLE_RESP"],
	USER_QUIT_REQ: [40024, "USER_QUIT_REQ"],
	USER_QUIT_RESP: [40025, "USER_QUIT_RESP"],
	FORCE_OFFLINE_REQ: [40028, "FORCE_OFFLINE_REQ"],
	FORCE_OFFLINE_RESP: [40029, "FORCE_OFFLINE_RESP"],
	PUSH_DELAYQUIT_OFFLINE_MSG: [40031, "PUSH_DELAYQUIT_OFFLINE_MSG"],
	PUSH_KICKEDOUT_MSG: [40033, "PUSH_KICKEDOUT_MSG"],
	USER_STAY_IN_GAME_REQ: [40034, "USER_STAY_IN_GAME_REQ"],
	SET_CARDS_TEST: [40036, "SET_CARDS_TEST"],
	USER_ONBACK_REQ: [40038, "USER_ONBACK_REQ"],
	USER_ONBACK_RESP: [40039, "USER_ONBACK_RESP"],
	DELAY_CHECK_REQ: [40040, "DELAY_CHECK_REQ"],
	DELAY_CHECK_RESP: [40041, "DELAY_CHECK_RESP"],


}


module.exports = {
	RpcDefine: RpcDefine
};
