var RpcDefine = {
	HALL_REFRESH_COIN           : [100, "HallRefreshCoinRequest"],
	HALL_REFRESH_COIN_RESP      : [100, "HallRefreshCoinResponse"],
	APPLY_REQ                   : [40004, "c2s_apply"],
	APPLY_RESP                  : [40005, "s2c_apply"],
	DISAPPLY_REQ                : [40006, "c2s_disApply"],
	DISAPPLY_RESP               : [40007, "s2c_disApply"],
	PUSH_STATE_CHANGE_RESP      : [40009, "SendStateChangeResponse"],
//	JOIN_COIN_TABLE_REQ         : [40000, "c2s_joinTable"],
	JOIN_COIN_TABLE_RESP        : [40001, "s2c_joinTable"],
	GET_USERLIST_REQ            : [40020, "c2s_getUserList"],
	GET_USERLIST_RESP           : [40021, "s2c_getUserList"],
	QIANG_REQ                   : [40022, "c2s_qiang"],
	QIANG_RESP                  : [40023, "s2c_qiang"],
	PUSHBET_RESP                : [40024, "s2c_qiangPush"],
	PUSH_ROUND_RESULT_RESP      : [40025, "s2c_roundResult"],
	PUSH_USER_RECONNECT_REQ     : [40026, "c2s_reconnect"],
	PUSH_USER_RECONNECT_RESP    : [40027, "s2c_reconnect"],
	PUSH_RECONNECT_DATA_RESP    : [40028, "s2c_reconnect"],
	DELAYQUIT_OFFLINE_RESP      : [40029, "DelayQuitOfflineResponse"],
	KICKEDOUT                   : [40030, "KickedOutRequest"],
	SEND_COIN_REFRESH           : [40062, "SendCoinRefreshResponse"],
	SEND_OPERATE_REQ            : [40031, "c2s_sendOperate"],
	SEND_OPERATE_RESP           : [40032, "s2c_sendOperate"],
	SET_CARDS_TEST              : [40033, "SetCardsTest"],
	SYNC_PALYER_INFO_REQ        : [40034, "c2s_SyncPlayerInfo"],
	SYNC_PALYER_INFO_RESP       : [40035, "s2c_SyncPlayerInfo"],
	USER_ONBACK_REQ             : [40036, "c2s_userOnBack"],
	USER_ONBACK_RESP            : [40037, "s2c_userOnBack"],
	USER_QUIT_REQ               : [40038, "c2s_userQuit"],
	USER_QUIT_RESP              : [40039, "s2c_userQuit"],
	SEND_REMAIN_TIME            : [40040, "SendRemainTimeResponse"],
}

module.exports = {
	RpcDefine : RpcDefine
};